name: laravel-and-db-deploy

on:
  workflow_call

jobs:
  laravel-and-db-deploy:
    runs-on: ubuntu-latest
    needs: laravel-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from Git SHA
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy database with Helm
        run: |
          helm upgrade database ./cavea-back/k8s_helm/database \
            -f ./cavea-back/k8s_helm/database/values.yaml \
            --namespace cavea-back-namespace \
            --create-namespace \
            --install \
            --set mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Deploy backend with Helm
        run: |
          helm upgrade back ./cavea-back/k8s_helm/backend \
            -f ./cavea-back/k8s_helm/backend/values.yaml \
            --namespace cavea-back-namespace \
            --create-namespace \
            --install \
            --set db_password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --set image.tag=${{ steps.version.outputs.SHORT_SHA }}

      - name: Wait for backend pod to be ready
        run: |
          kubectl rollout status deployment/back-deployment -n cavea-back-namespace
      
      - name: Run Laravel migrations on cluster
        run: |
          kubectl exec deploy/back-deployment -n cavea-back-namespace -- \
          php artisan migrate --force

