namespace: cavea-back-dev

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "512Gi"
    cpu: "200m"

db_name: cavea_dev_db
mysql_root_password: "CHANGE_ME"

storage:
  size: "5Gi"