FROM dunglas/frankenphp:1-php8.3

# Installer dépendances système utiles à Composer et PHP
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

# Install system dependencies
RUN install-php-extensions \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    opcache \
    intl

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache \
    && rm -rf bootstrap/cache/config.php bootstrap/cache/services.php

EXPOSE 80

CMD ["frankenphp", "php-server", "-r", "public/"]