apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{.Release.Namespace}}
  labels:
      {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: "mysql-service.cavea-back-namespace.svc.cluster.local"
  DB_DATABASE: "cavea_db"
  DB_USERNAME: "root"
  MYSQL_ROOT_PASSWORD: "root"
  DB_PASSWORD: "root"
  DB_PORT: "3306"
  DB_CONNECTION: "mysql"