apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{.Release.Namespace}}
  labels:
      {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: "database-service.{{ .Release.Namespace }}.svc.cluster.local"
  DB_DATABASE: {{ .Values.db_name }}
  DB_USERNAME: "root"
  DB_PASSWORD: {{ .Values.db_password }}
  DB_PORT: "3306"
  DB_CONNECTION: "mysql"
  MAIL_MAILER: {{ .Values.mail_mailer | default "log" | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.mail_from_address | default "noreply@cavea.ovh" | quote }}
  MAIL_FROM_NAME: {{ .Values.mail_from_name | default "Cavea" | quote }}
  RESEND_KEY: {{ .Values.resend_key | default "" | quote }}