apiVersion: v1
kind: ConfigMap
metadata:
  name: cavea-back-config
  namespace: cavea-back-namespace
data:
  DB_HOST: "mysql-service.cavea-back-namespace.svc.cluster.local"
  DB_DATABASE: "cavea_db"
  DB_USERNAME: "root"
  MYSQL_ROOT_PASSWORD: "root"
  DB_PASSWORD: "root"
  DB_PORT: "3306"
  DB_CONNECTION: "mysql"