apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "database.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.db_name }}
  DB_USERNAME: "root"