export const REGIONS = [
  { id: 1, name: "Alsace" },
  { id: 2, name: "Beaujolais" },
  { id: 3, name: "Bordeaux" },
  { id: 4, name: "Bourgogne" },
  { id: 5, name: "Champagne" },
  { id: 6, name: "Corse" },
  { id: 7, name: "Jura" },
  { id: 8, name: "Languedoc" },
  { id: 9, name: "Roussillon" },
  { id: 10, name: "Lorraine" },
  { id: 11, name: "Provence" },
  { id: 12, name: "Savoie et Bugey" },
  { id: 13, name: "Sud-Ouest" },
  { id: 14, name: "Vallée de la Loire" },
  { id: 15, name: "Vallée du Rhône" },
  { id: 16, name: "Île-de-France" },
  { id: 17, name: "Poitou-Charentes" },
];

export const COLOURS = [
  { id: 1, name: "Rouge" },
  { id: 2, name: "Blanc" },
  { id: 3, name: "Rosé" },
  { id: 4, name: "Pétillant" },
  { id: 5, name: "Orange" },
  { id: 6, name: "Autre" },
];

export const GRAPE_VARIETIES = [
  { id: 33, name: "Aligoté" },
  { id: 20, name: "Aramon" },
  { id: 31, name: "Bourboulenc" },
  { id: 2, name: "Cabernet Franc" },
  { id: 1, name: "Cabernet Sauvignon" },
  { id: 10, name: "Carignan" },
  { id: 21, name: "Chardonnay" },
  { id: 48, name: "Chasselas" },
  { id: 23, name: "Chenin Blanc" },
  { id: 9, name: "Cinsault" },
  { id: 29, name: "Clairette" },
  { id: 39, name: "Colombard" },
  { id: 16, name: "Counoise" },
  { id: 15, name: "Fer Servadou" },
  { id: 35, name: "Folle Blanche" },
  { id: 5, name: "Gamay" },
  { id: 42, name: "Gewurztraminer" },
  { id: 7, name: "Grenache" },
  { id: 30, name: "Grenache Blanc" },
  { id: 37, name: "Gros Manseng" },
  { id: 46, name: "Jacquère" },
  { id: 11, name: "Malbec" },
  { id: 28, name: "Marsanne" },
  { id: 36, name: "Mauzac" },
  { id: 34, name: "Melon de Bourgogne" },
  { id: 3, name: "Merlot" },
  { id: 17, name: "Mondeuse" },
  { id: 8, name: "Mourvèdre" },
  { id: 49, name: "Muscat Blanc à Petits Grains" },
  { id: 50, name: "Muscat d'Alexandrie" },
  { id: 14, name: "Négrette" },
  { id: 38, name: "Petit Manseng" },
  { id: 12, name: "Petit Verdot" },
  { id: 32, name: "Picpoul" },
  { id: 44, name: "Pinot Blanc" },
  { id: 43, name: "Pinot Gris" },
  { id: 4, name: "Pinot Noir" },
  { id: 18, name: "Poulsard" },
  { id: 41, name: "Riesling" },
  { id: 40, name: "Rolle (Vermentino)" },
  { id: 27, name: "Roussanne" },
  { id: 47, name: "Savagnin" },
  { id: 22, name: "Sauvignon Blanc" },
  { id: 24, name: "Sémillon" },
  { id: 45, name: "Sylvaner" },
  { id: 6, name: "Syrah" },
  { id: 13, name: "Tannat" },
  { id: 19, name: "Trousseau" },
  { id: 25, name: "Ugni Blanc" },
  { id: 26, name: "Viognier" },
];

export const COLOUR_MAP: { [key: string]: string } = {
  "Rouge": "#8B0000",
  "Blanc": "#F5DEB3",
  "Rosé": "#FFB6C1",
  "Pétillant": "#FFD700",
  "Orange": "#FF8C00",
  "Autre": "#808080"
};