name: Backend CI

on:
  push:
    branches: [ main, dev, feature/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/jobs/common/laravel-tests.yaml

  sonarqube:
    needs: tests
    uses: ./.github/jobs/common/laravel-sonarqube.yaml

  package:
    needs: sonarqube
    uses: ./.github/jobs/common/laravel-package.yaml

  deploy:
    needs: package
    uses: ./.github/jobs/common/laravel-and-db-deploy.yaml