name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, dev, feature/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/laravel-tests.yml
    secrets: inherit

  sonarqube:
    needs: tests
    uses: ./.github/workflows/laravel-sonarqube.yml
    secrets: inherit

  package:
    needs: sonarqube
    uses: ./.github/workflows/laravel-package.yml
    secrets: inherit

  deploy:
    needs: package
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/laravel-deploy.yml
    secrets: inherit