name: Backend CI

on:
  push:
    branches: [ main, dev, feature/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  # tests:
  #   uses: ./.github/actions/common/Laravel-tests

  # sonarqube:
    # needs: tests
    - uses: ./.github/actions/Laravel-sonarqube

  # package:
  #   needs: sonarqube
  #   uses: ./.github/jobs/common/laravel-package.yaml

  # deploy:
  #   needs: package
  #   uses: ./.github/jobs/common/laravel-and-db-deploy.yaml