name: Backend CI

on:
  push:
    branches: [ main, dev, feature/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: jobs/common/laravel-tests.yaml@feature/ci-cd

  sonarqube:
    needs: tests
    uses: jobs/common/laravel-sonarqube.yaml@feature/ci-cd

  package:
    needs: sonarqube
    uses: jobs/common/laravel-package.yaml@feature/ci-cd

  deploy:
    needs: package
    uses: jobs/common/laravel-and-db-deploy.yaml@feature/ci-cd