name: Laravel CI

on:
  push:
    branches: [ main, dev, feature/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install Composer dependencies
        working-directory: cavea-back
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        working-directory: cavea-back
        run: cp .env.example .env

      - name: Generate app key
        working-directory: cavea-back
        run: php artisan key:generate

      - name: Run migrations
        working-directory: cavea-back
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force

      - name: Run tests
        working-directory: cavea-back
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test

  laravel-sonarqube:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25
        with:
          projectBaseDir: ./cavea-back
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  laravel-prepare:
    runs-on: ubuntu-latest
    needs: laravel-sonarqube
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables for substitution
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Generate .env.prod
        working-directory: ./cavea-back
        run: |
          cp .env.prod.example .env.prod
          envsubst < .env.prod.example > .env.prod

  laravel-package:
    runs-on: ubuntu-latest
    needs: laravel-sonarqube
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy .env.prod into build context
        run: |
          cp cavea-back/.env.prod cavea-back/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cavea-back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cavea-back:1.0.4
            ${{ secrets.DOCKERHUB_USERNAME }}/cavea-back:latest

  laravel-deploy:
    runs-on: ubuntu-latest
    needs: laravel-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f deployment.yaml -n cavea-back-namespace
          kubectl apply -f service.yaml -n cavea-back-namespace
          kubectl apply -f ingress.yaml -n cavea-back-namespace
